-- =============================================================================
-- UNA SOLA TABLA events: eventos creados por admin o por el formulario de participación.
-- Estado: pending (no publicado) / published (visible en agenda).
-- Ejecutar en Supabase → SQL Editor → New query
-- =============================================================================

-- 1. Tabla events (crear si no existe)
CREATE TABLE IF NOT EXISTS public.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  date date NOT NULL,
  time text NOT NULL,
  iso_start timestamptz NOT NULL,
  iso_end timestamptz NOT NULL,
  location text NOT NULL,
  category text NOT NULL DEFAULT '',
  image text,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  visible boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'published',
  source text,
  contact_name text,
  contact_email text
);

COMMENT ON TABLE public.events IS 'Eventos de la agenda. Incluye propuestas del formulario (status=pending) y eventos publicados (status=published).';

-- Columnas añadidas si la tabla ya existía (ejecutar antes de COMMENT ON COLUMN)
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS visible boolean NOT NULL DEFAULT true;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS contact_name text;
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS contact_email text;

-- Añadir columna status: intentar ADD COLUMN y ignorar si ya existe
DO $$
BEGIN
  ALTER TABLE public.events ADD COLUMN status text NOT NULL DEFAULT 'published';
EXCEPTION
  WHEN duplicate_column THEN NULL;
END $$;

-- Comentarios de columnas (ya existen tras los ALTER anteriores)
COMMENT ON COLUMN public.events.visible IS 'Si false, no se muestra en la agenda (solo para status=published).';
COMMENT ON COLUMN public.events.status IS 'pending = no publicado, published = visible en agenda pública.';
COMMENT ON COLUMN public.events.source IS 'participation = enviado por formulario, admin = creado por administrador.';
COMMENT ON COLUMN public.events.contact_name IS 'Nombre de contacto (solo cuando source=participation).';
COMMENT ON COLUMN public.events.contact_email IS 'Email de contacto (solo cuando source=participation).';

-- Asegurar que filas existentes tengan status válido
UPDATE public.events SET status = 'published' WHERE status IS NULL OR status NOT IN ('pending', 'published');

-- Constraint de status
ALTER TABLE public.events DROP CONSTRAINT IF EXISTS events_status_check;
ALTER TABLE public.events ADD CONSTRAINT events_status_check CHECK (status IN ('pending', 'published'));

-- Trigger updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS events_updated_at ON public.events;
CREATE TRIGGER events_updated_at
  BEFORE UPDATE ON public.events
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- Trigger: si source = 'participation' en INSERT, forzar status = 'pending' (no usar default 'published')
CREATE OR REPLACE FUNCTION public.events_set_pending_for_participation()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.source = 'participation' THEN
    NEW.status := 'pending';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS events_set_pending_for_participation ON public.events;
CREATE TRIGGER events_set_pending_for_participation
  BEFORE INSERT ON public.events
  FOR EACH ROW EXECUTE PROCEDURE public.events_set_pending_for_participation();

-- 2. RLS: anónimos solo insertan con status=pending y solo leen publicados y visibles
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_events" ON public.events;
DROP POLICY IF EXISTS "anon_insert_events_pending" ON public.events;
DROP POLICY IF EXISTS "auth_select_events" ON public.events;
DROP POLICY IF EXISTS "auth_insert_events" ON public.events;
DROP POLICY IF EXISTS "auth_update_events" ON public.events;
DROP POLICY IF EXISTS "auth_delete_events" ON public.events;

-- Público: solo ver eventos publicados y visibles
CREATE POLICY "anon_select_events" ON public.events
  FOR SELECT TO anon
  USING (status = 'published' AND (visible IS NULL OR visible = true));

-- Formulario de participación: insertar solo con status = 'pending'
CREATE POLICY "anon_insert_events_pending" ON public.events
  FOR INSERT TO anon
  WITH CHECK (status = 'pending');

-- Autenticados: ver todo, insertar, actualizar, borrar
CREATE POLICY "auth_select_events" ON public.events FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_insert_events" ON public.events FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update_events" ON public.events FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_events" ON public.events FOR DELETE TO authenticated USING (true);
