-- =============================================================================
-- FASE 1: Perfiles de organización, visibilidad, consentimientos y directorio.
-- Ejecutar en Supabase → SQL Editor (después de auth/events existentes).
-- La app edita estos datos en /admin/cuenta (OrganizationProfileForm).
-- Logos: crear bucket organization_logos y ejecutar RUN_ORGANIZATION_LOGOS_STORAGE.sql.
-- =============================================================================

-- Nivel de visibilidad por campo (json field_visibility)
-- public = web abierta | community = solo sesión iniciada | private = solo dueño + moderadores

CREATE TABLE IF NOT EXISTS public.organization_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL UNIQUE REFERENCES auth.users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  name text NOT NULL,
  description text,
  themes text,
  territory text,
  organization_type text,

  contact_name text,
  contact_email text,
  contact_whatsapp text,

  seeks text,
  offers text,
  logo_url text,
  links jsonb NOT NULL DEFAULT '[]'::jsonb,

  willing_to_receive_contacts boolean NOT NULL DEFAULT false,
  participate_in_network_display boolean NOT NULL DEFAULT false,

  field_visibility jsonb NOT NULL DEFAULT '{
    "description": "community",
    "themes": "community",
    "territory": "community",
    "contact_name": "private",
    "contact_email": "private",
    "contact_whatsapp": "private",
    "seeks": "community",
    "offers": "community",
    "logo_url": "public",
    "links": "community",
    "willing_to_receive_contacts": "private",
    "participate_in_network_display": "private"
  }'::jsonb,

  consent_share_profile_with_orgs boolean NOT NULL DEFAULT false,
  consent_share_profile_with_orgs_at timestamptz,

  consent_receive_contact_requests boolean NOT NULL DEFAULT false,
  consent_receive_contact_requests_at timestamptz,

  consent_network_visualization boolean NOT NULL DEFAULT false,
  consent_network_visualization_at timestamptz,

  consent_connection_suggestions boolean NOT NULL DEFAULT false,
  consent_connection_suggestions_at timestamptz,

  directory_level text NOT NULL DEFAULT 'off'
    CHECK (directory_level IN ('off', 'community', 'public')),

  CONSTRAINT organization_profiles_directory_consent CHECK (
    directory_level = 'off' OR consent_share_profile_with_orgs = true
  )
);

COMMENT ON TABLE public.organization_profiles IS
  'Perfil de organización vinculado 1:1 a auth.users (owner). Directorio y campos filtrados por RPC.';

CREATE INDEX IF NOT EXISTS organization_profiles_directory_idx
  ON public.organization_profiles (directory_level)
  WHERE directory_level <> 'off';

-- Índices simples (sin pg_trgm): el filtro del directorio usa ILIKE; opcional activar pg_trgm en Extensions y añadir GIN si hace falta escala.
CREATE INDEX IF NOT EXISTS organization_profiles_themes_btree
  ON public.organization_profiles (themes text_pattern_ops);
CREATE INDEX IF NOT EXISTS organization_profiles_territory_btree
  ON public.organization_profiles (territory text_pattern_ops);
CREATE INDEX IF NOT EXISTS organization_profiles_org_type_btree
  ON public.organization_profiles (organization_type text_pattern_ops);

CREATE TABLE IF NOT EXISTS public.organization_profile_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.organization_profiles (id) ON DELETE CASCADE,
  revised_at timestamptz NOT NULL DEFAULT now(),
  revised_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  snapshot jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS organization_profile_revisions_profile_id_idx
  ON public.organization_profile_revisions (profile_id, revised_at DESC);

CREATE OR REPLACE FUNCTION public.organization_profiles_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS organization_profiles_updated_at ON public.organization_profiles;
CREATE TRIGGER organization_profiles_updated_at
  BEFORE UPDATE ON public.organization_profiles
  FOR EACH ROW EXECUTE PROCEDURE public.organization_profiles_set_updated_at();

CREATE OR REPLACE FUNCTION public.organization_profiles_revision_on_update()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.organization_profile_revisions (profile_id, revised_by, snapshot)
  VALUES (
    OLD.id,
    auth.uid(),
    to_jsonb(OLD)
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS organization_profiles_revision_on_update ON public.organization_profiles;
CREATE TRIGGER organization_profiles_revision_on_update
  BEFORE UPDATE ON public.organization_profiles
  FOR EACH ROW EXECUTE PROCEDURE public.organization_profiles_revision_on_update();

ALTER TABLE public.organization_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS organization_profiles_owner_select ON public.organization_profiles;
DROP POLICY IF EXISTS organization_profiles_owner_insert ON public.organization_profiles;
DROP POLICY IF EXISTS organization_profiles_owner_update ON public.organization_profiles;
DROP POLICY IF EXISTS organization_profiles_owner_delete ON public.organization_profiles;

CREATE POLICY organization_profiles_owner_select ON public.organization_profiles
  FOR SELECT TO authenticated USING (owner_id = auth.uid());

CREATE POLICY organization_profiles_owner_insert ON public.organization_profiles
  FOR INSERT TO authenticated WITH CHECK (owner_id = auth.uid());

CREATE POLICY organization_profiles_owner_update ON public.organization_profiles
  FOR UPDATE TO authenticated USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());

CREATE POLICY organization_profiles_owner_delete ON public.organization_profiles
  FOR DELETE TO authenticated USING (owner_id = auth.uid());

ALTER TABLE public.organization_profile_revisions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS organization_profile_revisions_owner ON public.organization_profile_revisions;
CREATE POLICY organization_profile_revisions_owner ON public.organization_profile_revisions
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.organization_profiles p
      WHERE p.id = profile_id AND p.owner_id = auth.uid()
    )
  );

-- Moderadores de eventos: ver perfiles (soporte)
DROP POLICY IF EXISTS organization_profiles_moderator_select ON public.organization_profiles;
CREATE POLICY organization_profiles_moderator_select ON public.organization_profiles
  FOR SELECT TO authenticated USING (public.is_events_moderator());

DROP POLICY IF EXISTS organization_profile_revisions_moderator_select ON public.organization_profile_revisions;
CREATE POLICY organization_profile_revisions_moderator_select ON public.organization_profile_revisions
  FOR SELECT TO authenticated USING (public.is_events_moderator());

-- ---------- Helpers: enmascarar campo según visibilidad ----------
CREATE OR REPLACE FUNCTION public._org_field_visible(
  p_level text,
  p_max_viewer text
) RETURNS boolean AS $$
BEGIN
  IF p_level IS NULL THEN RETURN false; END IF;
  IF p_max_viewer = 'public' THEN RETURN p_level = 'public'; END IF;
  IF p_max_viewer = 'community' THEN RETURN p_level IN ('public', 'community'); END IF;
  RETURN true;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION public._org_profile_card_json(
  rec public.organization_profiles,
  p_max_viewer text
) RETURNS jsonb AS $$
DECLARE
  fv jsonb := COALESCE(rec.field_visibility, '{}'::jsonb);
  out jsonb := jsonb_build_object('id', rec.id, 'name', rec.name);
BEGIN
  IF public._org_field_visible(fv->>'description', p_max_viewer) AND rec.description IS NOT NULL THEN
    out := out || jsonb_build_object('description', rec.description);
  END IF;
  IF public._org_field_visible(fv->>'themes', p_max_viewer) AND rec.themes IS NOT NULL THEN
    out := out || jsonb_build_object('themes', rec.themes);
  END IF;
  IF public._org_field_visible(fv->>'territory', p_max_viewer) AND rec.territory IS NOT NULL THEN
    out := out || jsonb_build_object('territory', rec.territory);
  END IF;
  IF rec.organization_type IS NOT NULL THEN
    out := out || jsonb_build_object('organization_type', rec.organization_type);
  END IF;
  IF public._org_field_visible(fv->>'contact_name', p_max_viewer) AND rec.contact_name IS NOT NULL THEN
    out := out || jsonb_build_object('contact_name', rec.contact_name);
  END IF;
  IF public._org_field_visible(fv->>'contact_email', p_max_viewer) AND rec.contact_email IS NOT NULL THEN
    out := out || jsonb_build_object('contact_email', rec.contact_email);
  END IF;
  IF public._org_field_visible(fv->>'contact_whatsapp', p_max_viewer) AND rec.contact_whatsapp IS NOT NULL THEN
    out := out || jsonb_build_object('contact_whatsapp', rec.contact_whatsapp);
  END IF;
  IF public._org_field_visible(fv->>'seeks', p_max_viewer) AND rec.seeks IS NOT NULL THEN
    out := out || jsonb_build_object('seeks', rec.seeks);
  END IF;
  IF public._org_field_visible(fv->>'offers', p_max_viewer) AND rec.offers IS NOT NULL THEN
    out := out || jsonb_build_object('offers', rec.offers);
  END IF;
  IF public._org_field_visible(fv->>'logo_url', p_max_viewer) AND rec.logo_url IS NOT NULL THEN
    out := out || jsonb_build_object('logo_url', rec.logo_url);
  END IF;
  IF public._org_field_visible(fv->>'links', p_max_viewer) AND jsonb_array_length(COALESCE(rec.links, '[]'::jsonb)) > 0 THEN
    out := out || jsonb_build_object('links', rec.links);
  END IF;
  IF public._org_field_visible(fv->>'willing_to_receive_contacts', p_max_viewer) THEN
    out := out || jsonb_build_object('willing_to_receive_contacts', rec.willing_to_receive_contacts);
  END IF;
  IF public._org_field_visible(fv->>'participate_in_network_display', p_max_viewer) THEN
    out := out || jsonb_build_object('participate_in_network_display', rec.participate_in_network_display);
  END IF;
  RETURN out;
END;
$$ LANGUAGE plpgsql STABLE;

-- ---------- Directorio ----------
CREATE OR REPLACE FUNCTION public.community_directory_search(
  p_theme text DEFAULT NULL,
  p_territory text DEFAULT NULL,
  p_org_type text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  viewer uuid := auth.uid();
  max_vis text;
  result jsonb := '[]'::jsonb;
  rec public.organization_profiles;
BEGIN
  IF viewer IS NULL THEN
    max_vis := 'public';
  ELSE
    max_vis := 'community';
  END IF;

  FOR rec IN
    SELECT p.*
    FROM public.organization_profiles p
    WHERE p.consent_share_profile_with_orgs = true
      AND p.directory_level <> 'off'
      AND (viewer IS NOT NULL OR p.directory_level = 'public')
      AND (p_theme IS NULL OR trim(p_theme) = '' OR p.themes ILIKE '%' || trim(p_theme) || '%')
      AND (p_territory IS NULL OR trim(p_territory) = '' OR p.territory ILIKE '%' || trim(p_territory) || '%')
      AND (p_org_type IS NULL OR trim(p_org_type) = '' OR p.organization_type ILIKE '%' || trim(p_org_type) || '%')
    ORDER BY p.name ASC
    LIMIT 200
  LOOP
    result := result || jsonb_build_array(public._org_profile_card_json(rec, max_vis));
  END LOOP;

  RETURN result;
END;
$$;

COMMENT ON FUNCTION public.community_directory_search IS
  'Directorio enmascarado: anónimo = campos public; autenticado = public+community.';

GRANT EXECUTE ON FUNCTION public.community_directory_search(text, text, text) TO anon;
GRANT EXECUTE ON FUNCTION public.community_directory_search(text, text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.community_directory_preview_levels()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'anonymous', 'Solo campos con visibilidad «Público».',
    'authenticated', 'Campos «Público» y «Comunidad». Nunca «Privado» salvo para tu propia cuenta.'
  );
$$;

GRANT EXECUTE ON FUNCTION public.community_directory_preview_levels() TO anon;
GRANT EXECUTE ON FUNCTION public.community_directory_preview_levels() TO authenticated;
