/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dejczezthzpeuxfxgvpx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlamN6ZXp0aHpwZXV4ZnhndnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5OTM2OTIsImV4cCI6MjA4MTU2OTY5Mn0.3zHzLYRWD6ETPKzgQW9-OMnHde8Y9PxEBfSz5sBu--I"