/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jvwtihesgbzixitfwxaf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2d3RpaGVzZ2J6aXhpdGZ3eGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0ODQ0OTcsImV4cCI6MjA4MTA2MDQ5N30.nb5cDSxrMh-8u8yW-8NnMDcVte0lqcO__7SYzWLnwik"